services:
    cassandra:
        image: cassandra:latest
        container_name: my-cassandra
        ports:
            - "9042:9042" 
        environment:
            - CASSANDRA_CLUSTER_NAME=MyTestCluster
            - CASSANDRA_DC=datacenter1
            - CASSANDRA_RACK=rack1
        volumes:
            - ./data/cassandra_data:/var/lib/cassandra

        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2.8g

        healthcheck:
            test: [ "CMD-SHELL", "cqlsh -u cassandra -p cassandra --debug | grep -q 'Connected to'" ]
            interval: 10s
            timeout: 5s
            retries: 10
